# Generated by Django 4.0.3 on 2022-04-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=128),
        ),
    ]
